image: python:latest

variables:
  TZ: "Asia/Shanghai"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CARDID: ""
  PASSWORD: ""
  SERVERCHANSCKEY: ""
  PPTOKEN: ""
  PPTOPIC: ""
  TGBOTTOKEN: ""
  TGCHATID: ""
  SUBSINFO: ""
  DELAYS: ""
  DELAYRAND: ""
  GPATOKEN: ""
  CORPID: ""
  CORPSECRET: ""
  AGENTID: ""

cache:
  paths:
    - .cache/pip

stages:
  - wait
  - run
  - retry

wait:
  stage: wait
  script:
    - echo "---Sleep $DELAYS---";
    - sleep $DELAYS
  rules:
    - if: $DELAYS != ""

run:
  stage: run
  script:
    - python -V  # Print out python version for debugging
    - python -m pip install --upgrade pip
    - pip install -r requirements-run.txt
    - echo "---Auto COVID Health Report---";
      if [ -z $DELAYRAND ] && [ -z $DELAYS ]; then 
      python LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt; else
      python LZU-Auto-COVID-Health-Report.py delayrand >> information.txt && cat information.txt; fi;
      if [ $? -eq 0 ]; then
      echo "---Notify Success---";
      python Notify-Result.py success $CI_JOB_URL; else
      echo "---Error logging and Notifying---";
      python Notify-Result.py failure $CI_JOB_URL && cat information.txt;
      exit 1; fi

retry:
  stage: retry
  script:
    - curl --request POST
      --form token=$GPATOKEN
      --form ref=main
      --form "variables[DELAYS]=30m"
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  rules:
    - if: $GPATOKEN != ""
      when: on_failure
