apiVersion: v1
kind: ConfigMap
metadata:
  name: lzu-auto-covid-health-report-configmap
data:
  delays: "30m"

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lzu-auto-covid-health-report
spec:
  schedule: "0 23 * 1,2,7,8 *"  # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lzu-auto-covid-health-report
            image: hollowman6/lzu-auto-covid-health-report:latest
            env:
              - name: DELAYS
                valueFrom:
                  configMapKeyRef:
                    name: lzu-auto-covid-health-report-configmap
                    key: delays
              - name: CARDID
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: cardid
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: password
              - name: SERVERCHANSCKEY
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: serverchansckey
              - name: OPENID
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: openid
              - name: PPTOKEN
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: pptoken
              - name: PPTOPIC
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: pptopic
              - name: TGBOTTOKEN
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: tgbottoken
              - name: TGCHATID
                valueFrom:
                  secretKeyRef:
                    name: lzu-auto-covid-health-report-secrets
                    key: tgchatid
            volumeMounts:
            - mountPath: /cache
              name: report-delays-marking
          volumes:
          - name: report-delays-marking
            emptyDir: {}
          restartPolicy: OnFailure
