name: Repo Sync

on: 
  push:
    branches:
      - main

jobs:
  gitee:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.login == "HollowMan6"
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: git@github.com:${{ github.repository }}.git
        destination-repo: git@gitee.com:${{ github.repository }}.git
